language: php

php:
    - 7.0
    - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 7.0
    - php: 7.1

before_install:
  - composer self-update

install:
  - composer update --prefer-source $COMPOSER_FLAGS